version: '3.8'

services:

  
  backend:
    build: ./backend
    container_name: laravel-backend
    ports:
      - "8000:80"        
    volumes:
      - ./backend:/var/www/html   
    depends_on:
      - database          
    environment:
      - APP_ENV=local

    frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"       
    depends_on:
      - backend

 
  database:
    image: mysql:8.0     
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myproject_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql    
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"        
    environment:
      PMA_HOST: database
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    depends_on:
      - database


volumes:
  db_data:
